/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree} from "@react-three/fiber";
import {a} from "react-spring"
import isLandScene  from "../assets/3D/islands.glb"

export function Model(props) {

  const islandRef = useRef();
  const {gl,viewport} = useThree()

  const { nodes, materials } = useGLTF(isLandScene)
  return (
    <a.group ref={islandRef} {...props} >
      <group position={[-1.541, 2.162, 1.136]} scale={[1.501, 1.181, 1.501]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface12_home_body_0.geometry}
          material={materials.home_body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1336_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1467_wood_0.geometry}
          material={materials.wood}
        />
      </group>
      <group
        position={[-0.686, 13.571, 2.281]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.34, 3.321, 4.929]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface16_roof1_0.geometry}
          material={materials.roof1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface16_windows_background_0.geometry}
          material={materials.windows_background}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface16_roof3_0.geometry}
          material={materials.roof3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface17_windows_frame_0.geometry}
          material={materials.windows_frame}
        />
      </group>


      <group position={[-0.686, 10.944, 4.73]} scale={[1.951, 2.312, 1.951]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface13_windows_frame_0.geometry}
          material={materials.windows_frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface14_wood2_0.geometry}
          material={materials.wood2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface727_wood2_0.geometry}
          material={materials.wood2}
        />
      </group>
    </a.group>
  )
}

useGLTF.preload('/foxs_islands.glb')
