/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree} from "@react-three/fiber";
import {a} from "react-spring"
import isLandScene  from "../assets/3D/islands.glb"

export function Model(props) {

  const islandRef = useRef();
  const {gl,viewport} = useThree()

  const { nodes, materials } = useGLTF(isLandScene)
  return (
    <a.group ref={islandRef} {...props} >
        <mesh
          geometry={nodes.polySurface986_tree_body_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.polySurface987_tree1_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.polySurface988_tree2_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.polySurface989_tree2_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.polySurface990_tree_body_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.polySurface991_tree_body_0.geometry}
          material={materials.PaletteMaterial001}
        />
    </a.group>
  )
}

useGLTF.preload('/foxs_islands.glb')
